'use strict';
const crypto=require('crypto');
const DATABASE_URL=process.env.DATABASE_URL||'';
const PUBLIC_ORIGIN=process.env.PUBLIC_ORIGIN||'https://miga-horno-vivo.onrender.com';
const SESSION_SECRET=process.env.SESSION_SECRET||crypto.createHash('sha256').update('miga-session:'+DATABASE_URL).digest('hex');
let pool=null,schemaPromise=null;
function db(){if(!DATABASE_URL)throw new Error('database_not_configured');if(!pool){const {Pool}=require('pg');pool=new Pool({connectionString:DATABASE_URL,max:4,idleTimeoutMillis:30000,connectionTimeoutMillis:10000})}return pool}
const query=(text,params=[])=>db().query(text,params);
const iso=v=>v?new Date(v).toISOString():null;
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const roundUp=(n,step=3)=>Math.ceil(Math.max(0,n)/step)*step;
function safeEqual(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function cookies(h=''){return Object.fromEntries(String(h).split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}))}
function corsOrigin(origin){return origin===PUBLIC_ORIGIN?origin:PUBLIC_ORIGIN}
function sendJson(res,status,data,origin=''){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':corsOrigin(origin),'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Access-Control-Allow-Credentials':'true','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'same-origin'});res.end(JSON.stringify(data))}
function readBody(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>100000){reject(new Error('payload_too_large'));req.destroy()}});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('invalid_json'))}})})}
async function ensureSchema(){if(schemaPromise)return schemaPromise;schemaPromise=(async()=>{await query(`CREATE TABLE IF NOT EXISTS miga_demand_intents (id text PRIMARY KEY,pickup_start timestamptz NOT NULL,pickup_end timestamptz NOT NULL,status text NOT NULL DEFAULT 'active',commitment text NOT NULL DEFAULT 'plan',customer_name text NOT NULL DEFAULT '',customer_contact text NOT NULL DEFAULT '',source text NOT NULL DEFAULT 'web',created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz)`);await query(`CREATE TABLE IF NOT EXISTS miga_demand_items (intent_id text NOT NULL,product_id text NOT NULL,qty integer NOT NULL,allocated_batch_id text NOT NULL DEFAULT '',allocated_qty integer NOT NULL DEFAULT 0,PRIMARY KEY(intent_id,product_id))`);await query(`CREATE TABLE IF NOT EXISTS miga_promotions (id text PRIMARY KEY,product_id text NOT NULL,kind text NOT NULL,buy_qty integer NOT NULL DEFAULT 1,pay_qty integer NOT NULL DEFAULT 1,discount_percent numeric(5,2) NOT NULL DEFAULT 0,title text NOT NULL,message text NOT NULL DEFAULT '',starts_at timestamptz NOT NULL DEFAULT now(),ends_at timestamptz NOT NULL,active boolean NOT NULL DEFAULT true,created_by text NOT NULL DEFAULT '',created_at timestamptz NOT NULL DEFAULT now())`);await query('CREATE INDEX IF NOT EXISTS idx_miga_demand_pickup ON miga_demand_intents(pickup_start,status)');await query('CREATE INDEX IF NOT EXISTS idx_miga_demand_product ON miga_demand_items(product_id,intent_id)');await query('CREATE INDEX IF NOT EXISTS idx_miga_promos_active ON miga_promotions(active,ends_at,product_id)')})().catch(e=>{schemaPromise=null;throw e});return schemaPromise}
async function audit(type,message,detail={}){try{await query('INSERT INTO audit(type,message,detail) VALUES($1,$2,$3::jsonb)',[type,message,JSON.stringify(detail||{})])}catch(e){console.warn('Demand audit:',e.message)}}
function readAdminToken(req){const token=cookies(req.headers.cookie||'').miga_session;if(!token)return null;const [body,sig]=token.split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',SESSION_SECRET).update(body).digest('base64url');if(!safeEqual(sig,expected))return null;try{const d=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));if(!d.exp||Date.now()>Number(d.exp))return null;return d}catch{return null}}
function permissions(role){if(role==='owner'||role==='manager')return{manageInventory:true,manageProduction:true};return{manageInventory:false,manageProduction:true}}
async function adminSession(req){const t=readAdminToken(req);if(!t)return null;if(t.legacy===true)return{...t,permissions:permissions('owner')};if(!t.userId)return null;const r=await query('SELECT user_id,email,name,access_status,role,session_version FROM miga_user_access WHERE user_id=$1::uuid LIMIT 1',[t.userId]);const x=r.rows[0];if(!x||x.access_status!=='approved'||Number(x.session_version||1)!==Number(t.sessionVersion||1))return null;return{userId:x.user_id,email:x.email,name:x.name,role:x.role,permissions:permissions(x.role)}}
async function requireAdmin(req,res,origin,permission='manageProduction'){const s=await adminSession(req);if(!s){sendJson(res,401,{ok:false,error:'AUTH_REQUIRED'},origin);return null}if(permission&&!s.permissions?.[permission]){sendJson(res,403,{ok:false,error:'FORBIDDEN'},origin);return null}return s}
function buildSlots(count=8){const out=[],d=new Date(Date.now()+10*60000),m=d.getUTCMinutes();d.setUTCMinutes(m<30?30:60,0,0);for(let i=0;i<count;i++){const start=new Date(d.getTime()+i*30*60000),end=new Date(start.getTime()+30*60000);out.push({start:start.toISOString(),end:end.toISOString()})}return out}
const newId=prefix=>`${prefix}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
async function promotions(){await ensureSchema();const r=await query(`SELECT pr.*,p.name product_name,p.price,p.image FROM miga_promotions pr JOIN products p ON p.id::text=pr.product_id WHERE pr.active=true AND pr.starts_at<=now() AND pr.ends_at>now() AND p.active=true ORDER BY pr.created_at DESC`);return r.rows.map(x=>({id:x.id,productId:x.product_id,productName:x.product_name,kind:x.kind,buyQty:Number(x.buy_qty),payQty:Number(x.pay_qty),discountPercent:Number(x.discount_percent||0),title:x.title,message:x.message,startsAt:iso(x.starts_at),endsAt:iso(x.ends_at),price:Number(x.price||0),image:x.image||''}))}
module.exports={db,query,iso,clamp,roundUp,corsOrigin,sendJson,readBody,ensureSchema,audit,requireAdmin,buildSlots,newId,promotions,crypto};
