const FACTORS=[
 {id:'salud',name:'Salud',icon:'♥',desc:'Energía, sueño, estabilidad física y mental.'},
 {id:'disciplina',name:'Disciplina',icon:'◆',desc:'Constancia, hábitos y capacidad de ejecutar.'},
 {id:'conocimiento',name:'Conocimiento',icon:'⌁',desc:'Aprendizaje técnico y comprensión profunda.'},
 {id:'comunicacion',name:'Comunicación',icon:'◌',desc:'Expresar ideas, escuchar y construir acuerdos.'},
 {id:'creatividad',name:'Creatividad',icon:'✦',desc:'Generar alternativas y resolver de forma original.'},
 {id:'resiliencia',name:'Resiliencia',icon:'↻',desc:'Recuperarte, ajustar estrategia y continuar.'}
];
let round=1,alloc={},snap1=null,snap2=null,timeLeft=30,timerId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function initAlloc(){alloc=Object.fromEntries(FACTORS.map(f=>[f.id,0]));}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1600)}
function total(){return Object.values(alloc).reduce((a,b)=>a+b,0)}
function remaining(){return 100-total()}
function startRound(n){round=n;initAlloc();renderFactors();$('#crisis').classList.toggle('show',n===2);$('#roundHeading').textContent=n===1?'Ronda 1 · Construye tu potencial':'Ronda 2 · Ahora todo cambió';$('#roundCopy').textContent=n===1?'Piensa en los próximos años. ¿Dónde pondrías tus recursos?':'Redistribuye desde cero después de que un proyecto importante fracasó.';timeLeft=30;updateHud();show('auction');clearInterval(timerId);timerId=setInterval(()=>{timeLeft--;updateHud();if(timeLeft<=0){clearInterval(timerId);if(remaining()===0)lockRound();else{timeLeft=0;toast('El tiempo terminó: usa las 100 monedas para continuar.')} }},1000)}
function updateHud(){$('#timer').textContent='00:'+String(Math.max(0,timeLeft)).padStart(2,'0');$('#remaining').textContent=remaining();$('#lockBtn').disabled=remaining()!==0;$('#lockBtn').textContent=remaining()===0?'Confirmar inversión':'Faltan '+remaining()+' monedas'}
function renderFactors(){const grid=$('#factorGrid');grid.innerHTML='';FACTORS.forEach(f=>{const v=alloc[f.id];const el=document.createElement('article');el.className='factor';el.innerHTML=`<div class="factorTop"><div><div class="icon">${f.icon}</div><div class="factorName">${f.name}</div></div><div class="amount">${v}<small>monedas</small></div></div><div class="factorDesc">${f.desc}</div><div class="range"><div class="fill" style="width:${v}%"></div></div><div class="controls"><button class="stepBtn minus" aria-label="Quitar 5">−</button><div class="quick"><button data-q="10">10</button><button data-q="20">20</button><button data-q="30">30</button></div><button class="stepBtn plus" aria-label="Agregar 5">+</button></div>`;
 el.querySelector('.minus').onclick=()=>change(f.id,-5);el.querySelector('.plus').onclick=()=>change(f.id,5);el.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>setVal(f.id,+b.dataset.q));grid.appendChild(el)});updateHud()}
function change(id,d){const nv=Math.max(0,Math.min(100,alloc[id]+d));const diff=nv-alloc[id];if(diff>remaining()){toast('No tienes suficientes monedas');return}alloc[id]=nv;renderFactors()}
function setVal(id,v){const diff=v-alloc[id];if(diff>remaining()){toast('Ese ajuste supera tus 100 monedas');return}alloc[id]=v;renderFactors()}
function lockRound(){clearInterval(timerId);if(remaining()!==0)return;if(round===1){snap1={...alloc};setTimeout(()=>startRound(2),350)}else{snap2={...alloc};renderComparison();show('compare')}}
function renderComparison(){const rows=$('#compareRows');rows.innerHTML='';let absDelta=0;FACTORS.forEach(f=>{const a=snap1[f.id],b=snap2[f.id],d=b-a;absDelta+=Math.abs(d);const row=document.createElement('div');row.className='compareRow';row.innerHTML=`<div class="compareLabel">${f.name}</div><div class="bars"><div class="barTrack"><div class="bar1" style="width:${a}%"></div></div><div class="barTrack"><div class="bar2" style="width:${b}%"></div></div></div><div class="delta ${d>0?'up':d<0?'down':'flat'}">${d>0?'+':''}${d}</div>`;rows.appendChild(row)});
 const score=Math.min(100,Math.round(42+absDelta*1.15));$('#scoreRing').style.setProperty('--score',score);$('#scoreText').textContent=score;const sorted=[...FACTORS].map(f=>({f,a:snap1[f.id],b:snap2[f.id],d:snap2[f.id]-snap1[f.id]})).sort((x,y)=>Math.abs(y.d)-Math.abs(x.d));const biggest=sorted[0];const strongest=[...FACTORS].sort((x,y)=>snap2[y.id]-snap2[x.id])[0];const low=[...FACTORS].sort((x,y)=>snap2[x.id]-snap2[y.id])[0];$('#insights').innerHTML=`<div class="insight"><b>Mayor cambio: ${biggest.f.name}</b><span>${biggest.d>0?'Subiste':'Bajaste'} ${Math.abs(biggest.d)} monedas. La crisis alteró claramente esa prioridad.</span></div><div class="insight"><b>Tu prioridad bajo presión: ${strongest.name}</b><span>Terminó con ${snap2[strongest.id]} monedas, la inversión más alta de la segunda ronda.</span></div><div class="insight"><b>Punto de tensión: ${low.name}</b><span>Recibió solo ${snap2[low.id]} monedas. Pregunta para discutir: ¿qué costo tendría descuidarlo durante mucho tiempo?</span></div>`}
function randGroup(){let base={salud:0,disciplina:0,conocimiento:0,comunicacion:0,creatividad:0,resiliencia:0};for(let p=0;p<24;p++){let w=FACTORS.map(()=>Math.random()*1.4+.35);let sum=w.reduce((a,b)=>a+b,0);FACTORS.forEach((f,i)=>base[f.id]+=Math.round(100*w[i]/sum));}FACTORS.forEach(f=>base[f.id]=Math.round(base[f.id]/24));let s=Object.values(base).reduce((a,b)=>a+b,0);base.disciplina+=100-s;return base}
function renderAudience(){const g=randGroup();const box=$('#audience');box.innerHTML='';FACTORS.forEach(f=>{const el=document.createElement('div');el.className='audCard';el.innerHTML=`<div class="top"><span>${f.icon} ${f.name}</span><strong>${g[f.id]}</strong></div><div class="audBar"><span style="width:${g[f.id]}%"></span></div>`;box.appendChild(el)})}
$('#startBtn').onclick=()=>startRound(1);$('#lockBtn').onclick=lockRound;$('#againBtn').onclick=()=>startRound(1);$('#projectorBtn').onclick=()=>{renderAudience();show('projector')};$('#showProjectorFromResults').onclick=()=>{renderAudience();show('projector')};$('#backHome').onclick=()=>show('home');$('#regenAudience').onclick=renderAudience;initAlloc();